Theme_Category:registry
Theme_Name:custom
Generic_Color:custom
Matugen:vibrant
Mode:dark
Preset:terminal

[Theme]
name = terminal-v2                   
# Display name for menus and notifications
description = terminal style version 2             
# One-line description
wallpaper = black.jpg               
# Filename relative to theme dir, or absolute path

[Colors]
preset_type = DMS             
# DMS | generic | matugen | path
preset_identifier = terminal       
# DMS: theme name   | generic: color name
# matugen: variant  | path: /full/path/theme.json
mode = dark                    
# dark | light

[Fonts]
family = Ac437 IBM EGA 8x8                  
# Font family for DMS UI and mangoWM jump/bar

[Borders]
thickness = 1               
# Bar border thickness (px) — also sets mangoWM borderpx
corner_radius = 0           
# UI + compositor corner radius (px)
widget_borders = 1         
# true | false — border around individual bar widgets

[Bars]
enabled_bars = 1           
# comma-separated: 1(top) 2(bottom) 3(top-status) 4(sidebar)

[Animations]
enabled = false                 
# true | false

[Dock]
enabled = false                 
# true | false