theme_name=arch
theme_wallpaper=arch-linux-xw0szpochzcu0gml.jpg
theme_preset_type=matugen
theme_preset_setting=vibrant
theme_mode=dark
theme_font="JetBrainsMono Nerd Font"
theme_border_thickness=1
theme_corner_radius=0
theme_bar1=false
theme_bar2=false
theme_bar3=true
theme_bar4=false
theme_dock=false
theme_frame=false
theme_animations=0
theme_fetch_logo=SDG-FETCH/archlinux
theme_fetch_conf=SDG-FETCH/arch.jsonc