[Theme]
name =
description =
wallpaper =

[Colors]
preset_type =         # DMS | generic | matugen | path
preset_identifier =   # DMS: theme name   | generic: color name
                      # matugen: variant  | path: /full/path/theme.json
mode =                # dark | light

[Fonts]
family =

[Borders]
thickness =           # px
corner_radius =       # px
widget_borders =      # true | false

[Bars]
enabled_bars =        # comma-separated: top, bottom, left, right

[Animations]
enabled =             # true | false

[Dock]
enabled =             # true | false
