#!/bin/bash

SELECTED="$1"

which matugen-compile && matugen-compile


WP_DIR=~/.local/themes

WP_CATEGORIES=$(ls "$WP_DIR" -1 )

echo "WP_CATEGORIES = $WP_CATEGORIES"

WP_GROUPS=""

for CAT in $WP_CATEGORIES; do 
    THEMES=$(ls "$WP_DIR/$CAT" -1)
    for THEME in $THEMES; do
        WP_GROUPS="$WP_GROUPS
$CAT/$THEME"
    done
done

if [[ $SELECTED == "" ]]; then

    SELECTED=$(echo "$WP_GROUPS" | fzf --layout=reverse)
fi
echo "user selected $SELECTED"

dms ipc call wallpaper set "$WP_DIR/$SELECTED/$(ls -1 "$WP_DIR/$SELECTED" | grep -v ".conf" | head -n 1)"
sleep 0.2
dms ipc call wallpaper next
dms ipc call wallpaper prev



## todo: add other settings

# fetch info from file
source $WP_DIR/$SELECTED/theme.conf


# handle preset type and setting
echo "handling colors"
sleep 0.2
theme_preset_type=matugen
theme_preset_setting=vibrant

case $theme_preset_type in
    matugen)
    dms ipc call settings set currentThemeCategory dynamic
    dms ipc call settings set matugenScheme scheme-$theme_preset_setting
    ;;
    dms)
    dms ipc call settings set currentThemeCategory registry
    dms ipc call settings set customThemeFile "/home/$(whoami)/.config/DankMaterialShell/themes/$theme_preset_setting/theme.json"
    ;;
    directory)
    dms ipc call settings set currentThemeCategory custom
    dms ipc call settings set customThemeFile "$theme_preset_setting"
    ;;
    color)
    dms ipc call settings set currentThemeCategory generic
    dms ipc call settings set currentThemeName $theme_preset_setting
    ;;

esac
# handle theme mode
echo "handling theme mode"
sleep 0.2
theme_mode=dark
dms ipc call theme $theme_mode


# handle borders
echo "handling borders"
sleep 0.2
theme_border_thickness=2
theme_corner_radius=8
dms ipc call settings set mangoLayoutBorderSize "$theme_border_thickness"
dms ipc call settings set cornerRadius "$theme_corner_radius"
dms ipc call settings set mangoLayoutRadiusOverride "$theme_corner_radius"

# handle font
echo "handling font"
sleep 0.2
theme_font="JetBrainsMono Nerd Font"
theme_animations=0
MANGO_FONT_CONF="$HOME/.config/mango/sdg-font.conf"
mkdir -p "$(dirname "$MANGO_FONT_CONF")"
cat > "$MANGO_FONT_CONF" <<- EOF
	# Generated by sdg-theme-select-v2.sh
	jump_label_decorate_font_desc = $theme_font 12
	tab_bar_decorate_font_desc = $theme_font 20
    group_bar_decorate_border_width = $theme_border_thickness
    group_bar_decorate_corner_radius = $theme_corner_radius
    jump_label_decorate_border_width = $theme_border_thickness
    jump_label_decorate_corner_radius = $theme_corner_radius
    animations = $theme_animations
	EOF
# handle bars
echo "handling bars"
sleep 0.2
if [ "$theme_bar1" == "true" ]; then
    dms ipc call bar reveal index 0

else
    dms ipc call bar hide index 0
fi
if [ "$theme_bar2" == "true" ]; then
    dms ipc call bar reveal index 1

else
    dms ipc call bar hide index 1
fi
if [ "$theme_bar3" == "true" ]; then
    dms ipc call bar reveal index 2

else
    dms ipc call bar hide index 2
fi
if [ "$theme_bar4" == "true" ]; then
    dms ipc call bar reveal index 3

else
    dms ipc call bar hide index 3
fi



# handle dock
theme_dock=false
echo "handling dock"
sleep 0.2
if [ "$theme_dock" == "true" ]; then
    dms ipc call settings set showDock true
    dms ipc call dock reveal
else
    dms ipc call settings set showDock false
    dms ipc call dock hide 
fi

# handle frame
theme_frame=false
echo "handling frame"
sleep 0.2
if [ "$theme_frame" == "true" ]; then
    dms ipc call settings set frameEnabled true
else
    dms ipc call settings set frameEnabled false
fi

