#!/bin/bash

SELECTED="$1"
CURTHEME=$(cat $HOME/.config/theme.state)
WP_DIR=~/.local/themes
case $SELECTED in
    clone)
    echo "[sdgtheme] cloning $CURTHEME"
    echo "please provide a new name:"
    read -p "theme name: user/" THEMENAME
    mkdir -p $WP_DIR/user
    cp -r $WP_DIR/$CURTHEME $WP_DIR/user/$THEMENAME
    read -n 1 -p "do you want to switch to this theme now? (y/N): " CHOICE
    if [ "$CHOICE" == "y" ]; then
        sdgtheme user/$THEMENAME
    fi
    exit 0
    ;;
    edit)
    ${EDITOR:-micro} $WP_DIR/$CURTHEME/theme.conf
    read -n 1 -p "do you want to reload the theme now? (y/N): " CHOICE
    if [ "$CHOICE" == "y" ]; then
        sdgtheme $CURTHEME
    fi
    exit 0
    ;;
    help)
    echo "[sdgtheme]"
    echo ""
    echo "commands:"
    echo "sdgtheme - shows the interactive FZF theme picker"
    echo "sdgtheme <theme> - applies that theme"
    echo "sdgtheme clone - clones your current theme to a new theme under the user/ category"
    echo "sdgtheme edit - edits your current theme"
    exit 0
    ;;
esac

which matugen-compile && matugen-compile

# source optional config
CONF_FILE="$HOME/.config/SDG-THEMES/sdg-themes.conf"
[ -f "$CONF_FILE" ] && source "$CONF_FILE"



WP_CATEGORIES=$(ls "$WP_DIR" -1 )

echo "WP_CATEGORIES = $WP_CATEGORIES"

WP_GROUPS=""

for CAT in $WP_CATEGORIES; do 
    THEMES=$(ls "$WP_DIR/$CAT" -1)
    for THEME in $THEMES; do
        WP_GROUPS="$WP_GROUPS
$CAT/$THEME"
    done
done

if [[ $SELECTED == "" ]]; then

    SELECTED=$(echo "$WP_GROUPS" | fzf --layout=reverse)
fi
echo "user selected $SELECTED"
echo "setting wallpaper"
dms ipc call wallpaper set "$WP_DIR/$SELECTED/$(ls -1 "$WP_DIR/$SELECTED" | grep -v ".conf" | head -n 1)"
sleep 0.2
dms ipc call wallpaper next
dms ipc call wallpaper prev
sleep 0.01
echo "$SELECTED" > ~/.config/theme.state

## todo: add other settings

# fetch info from file
source $WP_DIR/$SELECTED/theme.conf



# handle preset type and setting
echo "handling colors"
sleep 1
echo "preset type: $theme_preset_type"
echo "preset setting: $theme_preset_setting"
case $theme_preset_type in
    matugen)
    echo "setting matugen scheme to $theme_preset_setting"
    ThemeCategory=dynamic
    Matugen=$theme_preset_setting
    ThemeName=dynamic
    Preset="/home/$(whoami)/.config/DankMaterialShell/themes/$theme_preset_setting/theme.json"
    ;;
    DMS|dms|Dms)
    echo "setting theme file to $theme_preset_setting"
    ThemeCategory=custom
    Matugen=vibrant
    ThemeName=custom
    Preset="/home/$(whoami)/.config/DankMaterialShell/themes/$theme_preset_setting/theme.json"
    ;;
    directory)
    echo "setting theme file to $theme_preset_setting"
    ThemeCategory=custom
    Matugen=vibrant
    ThemeName=custom
    Preset="$theme_preset_setting"
    ;;
    color)
    echo "setting theme name to $theme_preset_setting"
    ThemeCategory=generic
    Matugen=vibrant
    ThemeName=$theme_preset_setting
    Preset=none
    ;;

esac

#generic is registry
dms ipc call settings set currentThemeCategory $ThemeCategory


# auto > matugen template
dms ipc call settings set matugenScheme scheme-$Matugen

dms ipc call settings set currentThemeName $ThemeName
# browse > preset
dms ipc call settings set customThemeFile "$Preset"
sleep 0.2
dms restart
sleep 2
dms ipc call theme toggle
dms ipc call theme toggle 

# handle font
sdgfont $theme_font
sleep 2

# handle theme mode
echo "handling theme mode"
echo "mode is $theme_mode"
sleep 0.2
dms ipc call theme $theme_mode
sleep 0.01

# handle borders
echo "handling borders"
echo "thickness: $theme_border_thickness"
echo "radius: $theme_corner_radius"
sleep 0.2

echo "setting mango border size to $theme_border_thickness"
dms ipc call settings set mangoLayoutBorderSize "$theme_border_thickness" # didnt apply
sleep 0.01
echo "setting corner radius to $theme_corner_radius"
dms ipc call settings set cornerRadius "$theme_corner_radius"
sleep 0.01
echo "setting mango corner radius to $theme_corner_radius"
dms ipc call settings set mangoLayoutRadiusOverride "$theme_corner_radius" # didnt apply
sleep 0.01
# handle font
echo "handling font"
sleep 0.2
MANGO_FONT_CONF="$HOME/.config/mango/theme-overrides.conf"
mkdir -p "$(dirname "$MANGO_FONT_CONF")"
cat > "$MANGO_FONT_CONF" <<- EOF
	# Generated by sdg-theme-select-v2.sh
	group_bar_decorate_border_width = $theme_border_thickness
	group_bar_decorate_corner_radius = $theme_corner_radius
	jump_label_decorate_border_width = $theme_border_thickness
	jump_label_decorate_corner_radius = $theme_corner_radius
	animations = $theme_animations
	EOF
echo "configuration:"
cat "$MANGO_FONT_CONF"
# apply font to other targets (DMS, Ghostty, VSCode, Waybar)


# generate corner radius CSS for Waybar
echo "handling corner radius css"
RADIUS_CSS_DIR="$HOME/.config/SDG-WAYSHELL-CONFIGS"
mkdir -p "$RADIUS_CSS_DIR"
cat > "$RADIUS_CSS_DIR/theme-overrides.css" <<- EOF
	* {
	    border-radius: ${theme_corner_radius}px;
	}
	EOF
MONOCLE_CSS_DIR="$HOME/.config/SDG-MONOCLE"
if [ -d "$MONOCLE_CSS_DIR" ]; then
    cat > "$MONOCLE_CSS_DIR/theme-overrides.css" <<- EOF
	* {
	    border-radius: ${theme_corner_radius}px;
	}
	EOF
fi
# handle bars
echo "handling bars"
echo "bar 1: $theme_bar1"
echo "bar 2: $theme_bar2"
echo "bar 3: $theme_bar3"
echo "bar 4: $theme_bar4"
sleep 0.2
if [ "$theme_bar1" == "true" ]; then
    dms ipc call bar reveal index 0

else
    dms ipc call bar hide index 0
fi
echo "handled bar 1"
sleep 0.01
if [ "$theme_bar2" == "true" ]; then
    dms ipc call bar reveal index 1

else
    dms ipc call bar hide index 1
fi
echo "handled bar 2"
sleep 0.01
if [ "$theme_bar3" == "true" ]; then
    dms ipc call bar reveal index 2

else
    dms ipc call bar hide index 2
fi
echo "handled bar 3"
sleep 0.01
if [ "$theme_bar4" == "true" ]; then
    dms ipc call bar reveal index 3

else
    dms ipc call bar hide index 3
fi
echo "handled bar 4"
sleep 0.01



# handle dock
echo "handling dock"
echo "dock mode: $theme_dock"
sleep 0.2
if [ "$theme_dock" == "true" ]; then
    dms ipc call settings set showDock true
    dms ipc call dock reveal
else
    dms ipc call settings set showDock false
    dms ipc call dock hide 
fi
sleep 0.01

# handle frame
echo "handling frame"
echo "frame mode: $theme_frame"
sleep 0.2
if [ "$theme_frame" == "true" ]; then
    dms ipc call settings set frameEnabled true
else
    dms ipc call settings set frameEnabled false
fi
sleep 0.01

# handle fastfetch via sdgfetch
echo "handling fastfetch"
sleep 0.2
if command -v sdgfetch >/dev/null 2>&1 && [ "$apply_fastfetch" != "false" ]; then
    [ -n "$theme_fetch_logo" ] && sdgfetch setlogo "$theme_fetch_logo"
    [ -n "$theme_fetch_conf" ] && sdgfetch setconf "$theme_fetch_conf"
    echo "sdgfetch: logo=$theme_fetch_logo conf=$theme_fetch_conf"
fi
sleep 0.01



