theme_name=cute
theme_wallpaper=QuCwdHB.png
theme_preset_type=generic
theme_preset_setting=coral
theme_mode=light
theme_font="VictorMono Nerd Font"
theme_border_thickness=1
theme_corner_radius=16
theme_bar1=true
theme_bar2=true
theme_bar3=false
theme_bar4=false
theme_dock=true
theme_frame=false
theme_animations=1
theme_fetch_logo=pusheen
theme_fetch_conf=ascii-art.jsonc