[Theme]
name = surface
description = surface theme
wallpaper = windows-11-blue-stock-white-background-light-official-2880x1800-5616.jpg

[Colors]
preset_type = matugen
preset_identifier = vibrant
mode = dark

[Fonts]
family = JetBrainsMono Nerd Font

[Borders]
thickness = 2
corner_radius = 8
widget_borders = false

[Bars]
enabled_bars = 1

[Animations]
enabled = true

[Dock]
enabled = false
