theme_name=surface
theme_wallpaper=windows-11-blue-stock-white-background-light-official-2880x1800-5616.jpg
theme_preset_type=DMS
theme_preset_setting=microsoft
theme_mode=light
theme_font="JetBrainsMono Nerd Font"
theme_border_thickness=2
theme_corner_radius=8
theme_bar1=true
theme_bar2=false
theme_bar3=true
theme_bar4=false
theme_dock=false
theme_frame=false
theme_animations=1