theme_name=solitude
theme_wallpaper=1-on-pole.jpg
theme_preset_type=matugen
theme_preset_setting=vibrant
theme_mode=dark
theme_font="IosevkaTerm Nerd Font"
theme_border_thickness=1
theme_corner_radius=0
theme_bar1=false
theme_bar2=false
theme_bar3=false
theme_bar4=false
theme_dock=false
theme_frame=false
theme_animations=0
theme_fetch_logo=solitude
theme_fetch_conf=os.jsonc