[Theme]
name = modus
description = modus theme
wallpaper = WF2vA9R.png

[Colors]
preset_type = DMS
preset_identifier = modus
mode = dark

[Fonts]
family = JetBrainsMono Nerd Font

[Borders]
thickness = 2
corner_radius = 8
widget_borders = false

[Bars]
enabled_bars = 1

[Animations]
enabled = true

[Dock]
enabled = false
