theme_name=framework
theme_wallpaper=framework-wallpaper-v0-ot5khsew6rmc1.jpg
theme_preset_type=DMS
theme_preset_setting=framework
theme_mode=dark
theme_font="JetBrainsMono Nerd Font"
theme_border_thickness=1
theme_corner_radius=10
theme_bar1=true
theme_bar2=false
theme_bar3=false
theme_bar4=false
theme_dock=false
theme_frame=false
theme_animations=1
theme_fetch_logo=framework
theme_fetch_conf=minimal.jsonc