theme_name=ethereal
theme_wallpaper=1-color-fade.png
theme_preset_type=matugen
theme_preset_setting=vibrant
theme_mode=dark
theme_font="IosevkaTerm Nerd Font Mono"
theme_border_thickness=1
theme_corner_radius=16
theme_bar1=false
theme_bar2=false
theme_bar3=false
theme_bar4=false
theme_dock=true
theme_frame=false
theme_animations=1
theme_fetch_logo=SDG-FETCH/none
theme_fetch_conf=SDG-FETCH/framed-dots.jsonc