theme_name=risetto
theme_wallpaper=1-color-curves.jpg
theme_preset_type=matugen
theme_preset_setting=vibrant
theme_mode=dark
theme_font="VictorMono Nerd Font"
theme_border_thickness=2
theme_corner_radius=10
theme_bar1=false
theme_bar2=true
theme_bar3=true
theme_bar4=false
theme_dock=true
theme_frame=false
theme_animations=1
theme_fetch_logo=risetto
theme_fetch_conf=simple-leftbar.jsonc