theme_name=great-wave
theme_wallpaper=1-kanagawa.jpg
theme_preset_type=matugen
theme_preset_setting=vibrant
theme_mode=light
theme_font="MesloLGL Nerd Font"
theme_border_thickness=2
theme_corner_radius=10
theme_bar1=false
theme_bar2=false
theme_bar3=false
theme_bar4=true
theme_dock=true
theme_frame=false
theme_animations=1
theme_fetch_logo=SDG-FETCH/grandma
theme_fetch_conf=SDG-FETCH/ascii-art.jsonc