theme_name=mac
theme_wallpaper=wp14362516.jpg
theme_preset_type=DMS
theme_preset_setting=macbook
theme_mode=light
theme_font="MesloLGL Nerd Font"
theme_border_thickness=2
theme_corner_radius=12
theme_bar1=true
theme_bar2=false
theme_bar3=true
theme_bar4=false
theme_dock=true
theme_frame=false
theme_animations=1