[Theme]
name = terminal
description = terminal theme
wallpaper = black.jpg

[Colors]
preset_type = DMS
preset_identifier = terminal
mode = dark

[Fonts]
family = Ac437 IBM EGA 8x8

[Borders]
thickness = 2
corner_radius = 0
widget_borders = false

[Bars]
enabled_bars = 4

[Animations]
enabled = false

[Dock]
enabled = false
