theme_name=catppuccin-latte
theme_wallpaper=1-color-fade.png
theme_preset_type=DMS
theme_preset_setting=catppuccin
theme_mode=light
theme_font="VictorMono Nerd Font"
theme_border_thickness=2
theme_corner_radius=10
theme_bar1=false
theme_bar2=false
theme_bar3=true
theme_bar4=false
theme_dock=true
theme_frame=true
theme_animations=1