[Theme]
name = catppuccin-latte
description = catppuccin-latte theme
wallpaper = 1-color-fade.png

[Colors]
preset_type = DMS
preset_identifier = catppuccin
mode = light

[Fonts]
family = JetBrainsMono Nerd Font

[Borders]
thickness = 2
corner_radius = 8
widget_borders = false

[Bars]
enabled_bars = 1

[Animations]
enabled = true

[Dock]
enabled = false
