theme_name=great-wave-dark
theme_wallpaper=1-kanagawa.jpg
theme_preset_type=matugen
theme_preset_setting=vibrant
theme_mode=dark
theme_font="MesloLGL Nerd Font"
theme_border_thickness=2
theme_corner_radius=8
theme_bar1=false
theme_bar2=false
theme_bar3=false
theme_bar4=true 
theme_dock=false
theme_frame=true
theme_animations=1