[Theme]
name = razer
description = razer theme
wallpaper = razer-dzbxa4ah6ky8sap7.jpg

[Colors]
preset_type = DMS
preset_identifier = razer
mode = dark

[Fonts]
family = JetBrainsMono Nerd Font

[Borders]
thickness = 2
corner_radius = 8
widget_borders = false

[Bars]
enabled_bars = 1

[Animations]
enabled = true

[Dock]
enabled = false
