theme_name=terminal-monochrome
theme_wallpaper=black.jpg
theme_preset_type=DMS
theme_preset_setting=terminal-mono
theme_mode=dark
theme_font="AcPlus IBM CGAthin-2y"
theme_border_thickness=1
theme_corner_radius=0
theme_bar1=false
theme_bar2=false
theme_bar3=false
theme_bar4=true
theme_dock=false
theme_frame=false
theme_animations=0