[Theme]
name = acer
description = acer theme
wallpaper = pmr48zw9xsx01.jpg

[Colors]
preset_type = DMS
preset_identifier = acerpredator
mode = dark

[Fonts]
family = JetBrainsMono Nerd Font

[Borders]
thickness = 2
corner_radius = 8
widget_borders = false

[Bars]
enabled_bars = 1

[Animations]
enabled = true

[Dock]
enabled = false
