theme_name=acer
theme_wallpaper=pmr48zw9xsx01.jpg
theme_preset_type=DMS
theme_preset_setting=acerpredator
theme_mode=dark
theme_font="JetBrainsMono Nerd Font"
theme_border_thickness=2
theme_corner_radius=6
theme_bar1=true
theme_bar2=false
theme_bar3=false
theme_bar4=false
theme_dock=false
theme_frame=false
theme_animations=1
theme_fetch_logo=acerpredator
theme_fetch_conf=Nex-Laptop.jsonc