[Theme]
name = tokyo-night
description = tokyo-night theme
wallpaper = 0-swirl-buck.jpg

[Colors]
preset_type = DMS
preset_identifier = tokyoNight
mode = dark

[Fonts]
family = JetBrainsMono Nerd Font

[Borders]
thickness = 2
corner_radius = 8
widget_borders = false

[Bars]
enabled_bars = 1

[Animations]
enabled = true

[Dock]
enabled = false
