theme_name=AMOLED
theme_wallpaper=black.jpg
theme_preset_type=DMS
theme_preset_setting=amoledBlack
theme_mode=dark
theme_font="JetBrainsMono Nerd Font"
theme_border_thickness=1
theme_corner_radius=12
theme_bar1=true
theme_bar2=false
theme_bar3=false
theme_bar4=false
theme_dock=false
theme_frame=false
theme_animations=0
theme_fetch_logo=SDG-FETCH/none
theme_fetch_conf=minimal.jsonc