theme_name=nord
theme_wallpaper=0kvzhru1ncua1.jpg
theme_preset_type=DMS
theme_preset_setting=nord
theme_mode=dark
theme_font="JetBrainsMono Nerd Font"
theme_border_thickness=2
theme_corner_radius=8
theme_bar1=true
theme_bar2=false
theme_bar3=false
theme_bar4=false
theme_dock=false
theme_frame=false
theme_animations=1