[Theme]
name = nord
description = nord theme
wallpaper = 0kvzhru1ncua1.jpg

[Colors]
preset_type = DMS
preset_identifier = nord
mode = dark

[Fonts]
family = JetBrainsMono Nerd Font

[Borders]
thickness = 2
corner_radius = 8
widget_borders = false

[Bars]
enabled_bars = 1

[Animations]
enabled = true

[Dock]
enabled = false
