theme_name=zenbook
theme_wallpaper=3840x2160-asus-zenbook-14-wallpaper-10th-gen-intel-v0-pf6v2uc8zkd71.jpg
theme_preset_type=DMS
theme_preset_setting=zenbook
theme_mode=light
theme_font="JetBrainsMono Nerd Font"
theme_border_thickness=2
theme_corner_radius=10
theme_bar1=true
theme_bar2=false
theme_bar3=false
theme_bar4=false
theme_dock=false
theme_frame=false
theme_animations=1
theme_fetch_logo=zenbook
theme_fetch_conf=simple-dots.jsonc