[Theme]
name = zenbook
description = zenbook theme
wallpaper = 3840x2160-asus-zenbook-14-wallpaper-10th-gen-intel-v0-pf6v2uc8zkd71.jpg

[Colors]
preset_type = DMS
preset_identifier = zenbook
mode = dark

[Fonts]
family = JetBrainsMono Nerd Font

[Borders]
thickness = 2
corner_radius = 8
widget_borders = false

[Bars]
enabled_bars = 1

[Animations]
enabled = true

[Dock]
enabled = false
