theme_name=lumon
theme_wallpaper=01-united-in-severance.jpg
theme_preset_type=matugen
theme_preset_setting=vibrant
theme_mode=dark
theme_font="AtkynsonMono Nerd Font"
theme_border_thickness=2
theme_corner_radius=8
theme_bar1=false
theme_bar2=true
theme_bar3=false
theme_bar4=false
theme_dock=true
theme_frame=false
theme_animations=1
theme_fetch_logo=SDG-FETCH/none
theme_fetch_conf=date-time.jsonc