#!/bin/bash
set -euo pipefail

# Skip if no font family configured
[[ -z "${FONT_FAMILY:-}" ]] && exit 0

# Apply font to DMS UI
dms ipc call settings set fontFamily "$FONT_FAMILY" 2>/dev/null || true

# Write font to separate mangoWM config file (outside dms/ so DMS won't overwrite)
MANGO_FONT_CONF="$HOME/.config/mango/sdg-font.conf"
mkdir -p "$(dirname "$MANGO_FONT_CONF")"
cat > "$MANGO_FONT_CONF" <<- EOF
	# Generated by sdg-theme-select-v2.sh
	jump_label_decorate_font_desc = $FONT_FAMILY 16
	tab_bar_decorate_font_desc = $FONT_FAMILY 16
	EOF

# Source it from mangoWM's config.conf if not already present
MANGO_CONFIG="$HOME/.config/mango/config.conf"
if [[ -f "$MANGO_CONFIG" ]] && ! grep -q "sdg-font.conf" "$MANGO_CONFIG"; then
    echo "source=~/.config/mango/sdg-font.conf" >> "$MANGO_CONFIG"
fi
