#!/bin/bash
# 10-fonts.sh — Set DMS font and mangoWM jump/bar font
# ------------------------------------------------------
# Applies the font family to:
#   1. DMS UI (settings set fontFamily)
#   2. mangoWM's group bar (tab_bar_decorate_font_desc)
#   3. mangoWM's jump mode labels (jump_label_decorate_font_desc)
#
# The mangoWM font values are written to a separate config file
# (sdg-font.conf) that is sourced from config.conf.  This keeps
# them outside the DMS-managed dms/ directory so they survive
# DMS regenerating its own config files.
# ------------------------------------------------------
set -euo pipefail

[[ -z "${FONT_FAMILY:-}" ]] && exit 0

# DMS UI font — the shell interface
dms ipc call settings set fontFamily "$FONT_FAMILY" 2>/dev/null || true

# mangoWM group bar + jump mode font
MANGO_FONT_CONF="$HOME/.config/mango/sdg-font.conf"
mkdir -p "$(dirname "$MANGO_FONT_CONF")"
cat > "$MANGO_FONT_CONF" <<- EOF
	# Generated by sdg-theme-select-v2.sh
	jump_label_decorate_font_desc = $FONT_FAMILY 16
	tab_bar_decorate_font_desc = $FONT_FAMILY 16
	EOF

# Ensure config.conf sources our font file
MANGO_CONFIG="$HOME/.config/mango/config.conf"
if [[ -f "$MANGO_CONFIG" ]] && ! grep -q "sdg-font.conf" "$MANGO_CONFIG"; then
    echo "source=~/.config/mango/sdg-font.conf" >> "$MANGO_CONFIG"
fi
