theme_name=gaming
theme_wallpaper=7XHLf.jpg
theme_preset_type=matugen
theme_preset_setting=vibrant
theme_mode=dark
theme_font="MonaspiceKr Nerd Font"
theme_border_thickness=3
theme_corner_radius=0
theme_bar1=true
theme_bar2=false
theme_bar3=false
theme_bar4=false
theme_dock=false
theme_frame=false
theme_animations=1