theme_name=destiny-void
theme_wallpaper=7 - SI3CAMJ.jpg
theme_preset_type=matugen
theme_preset_setting=vibrant
theme_mode=dark
theme_font="ZedMono Nerd Font"
theme_border_thickness=2
theme_corner_radius=12
theme_bar1=true
theme_bar2=false
theme_bar3=false
theme_bar4=false
theme_dock=false
theme_frame=false
theme_animations=0
theme_fetch_logo=destiny
theme_fetch_conf=minimal-colors.jsonc