[Theme]
name = aorus
description = aorus theme
wallpaper = wp8696389.jpg

[Colors]
preset_type = DMS
preset_identifier = gigabyteaorus
mode = dark

[Fonts]
family = JetBrainsMono Nerd Font

[Borders]
thickness = 2
corner_radius = 8
widget_borders = false

[Bars]
enabled_bars = 1

[Animations]
enabled = true

[Dock]
enabled = false
