theme_name=aorus
theme_wallpaper=wp8696389.jpg
theme_preset_type=DMS
theme_preset_setting=gigabyteaorus
theme_mode=dark
theme_font="JetBrainsMono Nerd Font"
theme_border_thickness=2
theme_corner_radius=10
theme_bar1=false
theme_bar2=true
theme_bar3=false
theme_bar4=false
theme_dock=false
theme_frame=false
theme_animations=1
theme_fetch_logo=aorus
theme_fetch_conf=Nex-Desktop.jsonc