theme_name=rose-pine
theme_wallpaper=1-funky-shapes.jpg
theme_preset_type=DMS
theme_preset_setting=rosePine
theme_mode=light
theme_font="VictorMono Nerd Font"
theme_border_thickness=2
theme_corner_radius=12
theme_bar1=true
theme_bar2=false
theme_bar3=false
theme_bar4=false
theme_dock=true
theme_frame=false
theme_animations=1
theme_fetch_logo=SDG-FETCH/rose
theme_fetch_conf=SDG-FETCH/screenfetch.jsonc