[Theme]
name = dell
description = dell theme
wallpaper = ombbhcnd6mq31.png

[Colors]
preset_type = DMS
preset_identifier = dellxps
mode = dark

[Fonts]
family = JetBrainsMono Nerd Font

[Borders]
thickness = 2
corner_radius = 8
widget_borders = false

[Bars]
enabled_bars = 1

[Animations]
enabled = true

[Dock]
enabled = false
