theme_name=system76
theme_wallpaper=system76-system76-logo-gray-by-kate-hazen-of-system76.jpg
theme_preset_type=DMS
theme_preset_setting=system76
theme_mode=dark
theme_font="Ubuntu Nerd Font"
theme_border_thickness=2
theme_corner_radius=10
theme_bar1=true
theme_bar2=false
theme_bar3=false
theme_bar4=false
theme_dock=false
theme_frame=false
theme_animations=1
theme_fetch_logo=system76
theme_fetch_conf=archey.jsonc