Theme_Category: # color = generic, auto = dynamic, preset = registry
Generic_Color: # blue, purple, green, orange, red, cyan, pink, amber, coral, white. put dynamic for dynamic and custom for presets.
Matugen: # tonal-spot, vibrant, content, expressive, fidelity, fruit-salad, monochrome, neutral, rainbow
Mode: # light or dark
Preset: # run ls ~/.config/DankMaterialShell/themes, use the folder names directly.

