[Theme]
name = retro-82
description = retro-82 theme
wallpaper = 1-in-the-groove.jpg

[Colors]
preset_type = DMS
preset_identifier = retrobox
mode = dark

[Fonts]
family = Ubuntu Nerd Font

[Borders]
thickness = 2
corner_radius = 0
widget_borders = false

[Bars]
enabled_bars = 1

[Animations]
enabled = true

[Dock]
enabled = false
