theme_name=msi-dragon
theme_wallpaper=d9lv3aq-234fcc89-da86-4a45-a5a7-f3fad31984f7.jpg
theme_preset_type=DMS
theme_preset_setting=msigaming
theme_mode=dark
theme_font="MonaspiceKr Nerd Font"
theme_border_thickness=3
theme_corner_radius=6
theme_bar1=true
theme_bar2=false
theme_bar3=false
theme_bar4=false
theme_dock=false
theme_frame=false
theme_animations=1
theme_fetch_logo=msi
theme_fetch_conf=very-fancy-2.jsonc