[Theme]
name = msi-dragon
description = msi-dragon theme
wallpaper = d9lv3aq-234fcc89-da86-4a45-a5a7-f3fad31984f7.jpg

[Colors]
preset_type = DMS
preset_identifier = msigaming
mode = dark

[Fonts]
family = JetBrainsMono Nerd Font

[Borders]
thickness = 2
corner_radius = 8
widget_borders = false

[Bars]
enabled_bars = 1

[Animations]
enabled = true

[Dock]
enabled = false
