[Theme]
name = ROG
description = ROG theme
wallpaper = Asus-HD-Wallpaper-Free-download.jpg

[Colors]
preset_type = DMS
preset_identifier = asusrog
mode = dark

[Fonts]
family = JetBrainsMono Nerd Font

[Borders]
thickness = 2
corner_radius = 8
widget_borders = false

[Bars]
enabled_bars = 1

[Animations]
enabled = true

[Dock]
enabled = false
