theme_name=WAN
theme_wallpaper=2.png
theme_preset_type=matugen
theme_preset_setting=vibrant
theme_mode=dark
theme_font="MonaspiceKr Nerd Font"
theme_border_thickness=2
theme_corner_radius=16
theme_bar1=false
theme_bar2=true
theme_bar3=false
theme_bar4=false
theme_dock=false
theme_frame=false
theme_animations=1