[Theme]
name = pride
description = pride theme
wallpaper = trans-1920-x-1080-background-8x3cu66nci5dqtjw.jpg

[Colors]
preset_type = matugen
preset_identifier = vibrant
mode = dark

[Fonts]
family = JetBrainsMono Nerd Font

[Borders]
thickness = 2
corner_radius = 8
widget_borders = false

[Bars]
enabled_bars = 1

[Animations]
enabled = true

[Dock]
enabled = false
